import "../globals.css";
import { powerCore } from "@/app/fonts";
export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={powerCore.variable}>
      <body>{children}</body>
    </html>
  );
}
